apiVersion: v1
kind: Pod
metadata: 
  name: empty-dir-demo
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  - name: almalinux
    image: almalinux:9
    volumeMounts:
    - mountpath: /var/log/nginx
      name: nginx-logs
      readOnly: false
  volumes:
  - name: nginx-logs
    emptyDir:
      sizelimit: 100Mi
